apiVersion: v1 # api server version to accept pod request 
kind: Pod # pod 
metadata:
  creationTimestamp: null
  labels: # label of my POD 
    x: helloashu # run is key and ashuwebpod is value 
  name: ashuwebpod # name of my POD 
spec:
  nodeName: minion1  # this is manual scheduling 
  containers:
  - image: dockerashu/customer1:v1 # image from docker hub 
    name: ashuwebpod # name of container 
    env: # create / replace env var value ku
    - name: myapp # name of env var 
      value: app3  # value of variable 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
